####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |                            ____   _                                                          | #
# |                          /  ___| (_)   ___    ___   _ __    ___                              | #
# |                          | |     | |  / __|  / _ \ | '__|  / _ \                             | #
# |                          | |___  | | | (__  |  __/ | |    | (_) |                            | #
# |                           \____| |_|  \___|  \___| |_|     \___/                             | #
# |                                                                                              | #
# |                                   Made by: Markus__27                                        | #
# |                                                                                              | #
# |  SOURCE CODE: https://github.com/ForgottenWorld/FWCicero                                     | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################

# Defines the time in milliseconds available for a player to use the Cicero.
# 48 hours
time: 172800000

# Defines the respawn point after the city tour
respawn:
  w: 'world'
  x: 18
  y: 68
  z: 188